version: '3.5'

networks:
  public:
    external:
      name: traefik_webgateway

services:
  app:
    build:
      args:
        - XDEBUG=true
        - NODE_JS=true
        #- WP_CLI=true
        - RELEASE_VERSION=apache
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - LOCALE=${LOCALE}
        - TZ=${TZ}
      context: .
    container_name: docker-project
    labels:
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:docker-project
      - traefik.port=80
    networks:
      - public
    #working_dir: /var/www/public
    volumes:
      - ./www:/var/www
