#!/usr/bin/env bash

cd "$(dirname "$0")"

if [ ! -f traefik/traefik.toml ]; then
    email=""

    if [ "$1" = "--email" ] && [ "$2" != "" ]; then
        email=$2
    else
        echo "Enter email address for Let's Encrypt SSL certificates:"

        read email
    fi

    cp traefik/traefik-sample.toml traefik/traefik.toml

    sed -i.bak "s/your-email@address/$email/g"  traefik/traefik.toml
    rm traefik/traefik.toml.bak

    echo "Created Traefik configuration file."
else
    echo "Traefik configuration file already exists."
fi

if [ ! -f services ]; then
    cp services-sample services
    echo "Created services file."
else
    echo "Services file already exists."
fi

if [ ! -f .build.env ]; then
    if [ -z "$TZ" ]; then
        echo "Finding time zone."
        dir=$(pwd)
        cd /usr/share/zoneinfo
        #https://superuser.com/a/639096
        TIME_ZONE="$(find * -type f -exec sh -c "diff -q /etc/localtime '{}' > /dev/null && echo {}" \;)"
        TIME_ZONE=($TIME_ZONE)
        TIME_ZONE="${TIME_ZONE[0]}"
        TZ=$TIME_ZONE
        echo "Time zone is: ${TZ}"
        cd $dir
    fi
    {
        echo "export USER_ID=$(id -u)";
        echo "export GROUP_ID=$(id -g)";
        echo "export TZ=$TZ";
    } > .build.env

    printf "\nCreated .build.env file.\n"
else
    echo "Build environment file (.build.env) already exists."
fi
