#!/usr/bin/env bash

cd "$(dirname "$0")"

if [[ ! -f traefik/traefik.toml ]]; then
    cp traefik/traefik-sample.toml traefik/traefik.toml

    echo "Created traefik.toml file."

    cert_filename="traefik"

    if [[ "$1" = "--cert-filename" ]]; then
        if [[ -n "$2" ]]; then
            cert_filename="$2"
        else
            echo "Error: SSL certificate file name is required."
            exit 1
        fi
    fi

    if [[ -f "traefik/cert/${cert_filename}.key" ]]; then
        echo "SSL certificate already exists."
    else
        traefik/create-cert --cert-filename "${cert_filename}"

        if [[ "${cert_filename}" != "traefik" ]]; then
            sed -i.bak "s/traefik.crt/${cert_filename}.crt/g" "traefik/traefik.toml"
            sed -i.bak "s/traefik.key/${cert_filename}.key/g" "traefik/traefik.toml"
            rm "traefik/traefik.toml.bak"
        fi

        echo "Created SSL certificate."
    fi
else
    echo "Traefik configuration file already exists."
fi

if [[ ! -f services ]]; then
    cp services-sample services
    echo "Created services file."
else
    echo "Services file already exists."
fi

if [[ ! -f .build.env ]]; then
    if [[ -z "${TZ}" ]]; then
        echo "Finding time zone."
        dir="$(pwd)"
        cd /usr/share/zoneinfo
        #https://superuser.com/a/639096
        TIME_ZONE=("$(find * -type f -exec sh -c "diff -q /etc/localtime '{}' > /dev/null && echo {}" \;)")
        TZ="${TIME_ZONE[0]}"
        echo "Time zone is: ${TZ}"
        cd "${dir}"
    fi

    if [[ -z "${LANG}" ]]; then
        echo "Warning: the environment variable LANG is not set!";
        read -p "Enter a locale: [en_US.UTF-8*] " LANG
        [[ -z "${LANG}" ]] && LANG="en_US.UTF-8"
    fi

    read -sp "Enter the database root user password: [secret*] " password
    echo ""

    [[ -z "${password}" ]] && password="secret"

    composer_dir="${HOME}/.composer"

    [[ -n "${COMPOSER_HOME}" ]] && composer_dir="${COMPOSER_HOME}"

    if [[ ! -d "${composer_dir}" ]]; then
        echo "Creating Composer directory: ${composer_dir}"
        mkdir -p "${composer_dir}"
    fi

    cp ".build-sample.env" ".build.env"
    sed -i.bak "s@export USER_ID=1000@export USER_ID=$(id -u)@" ".build.env"
    sed -i.bak "s@export GROUP_ID=1000@export GROUP_ID=$(id -g)@" ".build.env"
    sed -i.bak "s@export TIME_ZONE=UTC@export TIME_ZONE=${TZ}@" ".build.env"
    sed -i.bak "s@export LOCALE=en_US\.UTF-8@export LOCALE=${LANG}@" ".build.env"
    sed -i.bak "s@export DATABASE_ROOT_PASSWORD=secret@export DATABASE_ROOT_PASSWORD=${password}@" ".build.env"
    sed -i.bak "s@export COMPOSER_DIR=.*@export COMPOSER_DIR=${composer_dir}@" ".build.env"
    rm ".build.env.bak"

    echo "Created .build.env file."
else
    echo "Build environment file (.build.env) already exists."
fi
