#!/usr/bin/env bash

cd "$(dirname "$0")"

if [ ! -f traefik/traefik.toml ]; then
    email=""
    cert=""

    if [ "$1" = "--email" ] && [ "$2" != "" ]; then
        email=$2
    elif [ "$1" = "--create-cert" ]; then
        cert="yes"
    else
        read -p "Create a self signed certificate: (no/yes) " cert
        if [ "$cert" != "y" ] && [ "$cert" != "yes" ]; then
            read -p "Enter email address for Let's Encrypt SSL certificates: " email
        fi
    fi

    if [ "$cert" = "y" ] || [ "$cert" = "yes" ]; then
        if [ ! -f traefik/cert/traefik.crt ] || [ ! -f traefik/cert/traefik.key ]; then
            rm -f traefik/cert/traefik.crt
            rm -f traefik/cert/traefik.key
            traefik/create-cert
            echo "Created a self signed certificate."
        else
            echo "Self signed certificate file already exist."
        fi
        cp traefik/traefik-sample-cert.toml traefik/traefik.toml
        echo "Created Traefik configuration file."
    elif [ -n "$email" ]; then
        cp traefik/traefik-sample.toml traefik/traefik.toml

        sed -i.bak "s/your-email@address/$email/g"  traefik/traefik.toml
        rm traefik/traefik.toml.bak

        echo "Created Traefik configuration file."
    else
        echo "Error: create a self signed certificate or enter an email address for Let's Encrypt SSL certificates."
        exit 1
    fi
else
    echo "Traefik configuration file already exists."
fi

if [ ! -f services ]; then
    cp services-sample services
    echo "Created services file."
else
    echo "Services file already exists."
fi

if [ ! -f .build.env ]; then
    if [ -z "$TZ" ]; then
        echo "Finding time zone."
        dir=$(pwd)
        cd /usr/share/zoneinfo
        #https://superuser.com/a/639096
        TIME_ZONE="$(find * -type f -exec sh -c "diff -q /etc/localtime '{}' > /dev/null && echo {}" \;)"
        TIME_ZONE=($TIME_ZONE)
        TIME_ZONE="${TIME_ZONE[0]}"
        TZ=$TIME_ZONE
        echo "Time zone is: ${TZ}"
        cd $dir
    fi

    read -sp 'Enter the database root user password [secret]: ' password

    if [ "$password" = "" ]; then
        password="secret"
    fi

    {
        echo "export USER_ID=$(id -u)";
        echo "export GROUP_ID=$(id -g)";
        echo "export TZ=$TZ";
        echo -e "export DATABASE_ROOT_PASSWORD=$password"
    } > .build.env

    printf "\nCreated .build.env file.\n"
else
    echo "Build environment file (.build.env) already exists."
fi
