version: '3.5'

networks:
  public:
    external:
      name: traefik_webgateway

# https://adminer

services:
  adminer:
    container_name: adminer
    image: adminer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.rule=Host(`adminer`)"
      - "traefik.http.routers.adminer.tls=true"
    networks:
      - public
    restart: always
