version: '3.5'

volumes:
  mariadb:

networks:
  public:
    external:
      name: traefik_webgateway

services:
  # Use mariadb as the hostname in web apps. Use `docker-services mariadb ip-address` to retrieve the i.p. address
  # to use as the host in client applications such as MySQL Workbench.
  mariadb:
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      TZ: ${TZ}
    image: mariadb
    networks:
      - public
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
