version: '3.5'

volumes:
  mariadb:

networks:
  public:
    external:
      name: traefik_webgateway

services:
  # Use localhost as the hostname in client applications, e.g. MySQL Workbench, and mariadb in web apps.
  mariadb:
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      TZ: ${TZ}
    image: mariadb
    networks:
      - public
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
