version: '3.5'

volumes:
  mysql:

networks:
  public:
    external:
      name: traefik_webgateway

services:
  # Use mysql as the hostname in web apps.
  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      TZ: ${TZ}
    image: mysql
    networks:
      - public
    restart: always
    volumes:
      - mysql:/var/lib/mysql
