version: '3.5'

volumes:
  postgres:

networks:
  public:
    external:
      name: traefik_webgateway

services:
  # Use postgres as the hostname in web apps. Use `docker-services postgres ip-address` to retrieve the i.p. address
  # to use as the host in client applications such as pgAdmin.
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      TZ: ${TZ}
      PGTZ: ${TZ}
    image: postgres
    networks:
      - public
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
