#!/usr/bin/env bash

cert_dir="$( cd "$(dirname "$0")/cert" ; pwd -P )"

common_name="docker-project"
filename="traefik"

if [ "$1" = "--common-name" ] && [ -n "$2" ]; then
    common_name="$2"
elif [ "$3" = "--common-name" ] && [ -n "$4" ]; then
    common_name="$4"
fi

if [ "$1" = "--cert-filename" ] && [ -n "$2" ]; then
    filename="$2"
elif [ "$3" = "--cert-filename" ] && [ -n "$4" ]; then
    filename="$4"
fi

openssl req -subj "/commonName=*.${common_name}/" -x509 -nodes -days 9999 -newkey rsa:2048 -keyout "${cert_dir}/${filename}".key -out "${cert_dir}/${filename}".crt
