#!/usr/bin/env bash

cert_dir="$( cd "$(dirname "$0")/cert" ; pwd -P )"

common_name="docker-project"
filename="traefik"

if [ ! -z "$1" ]; then
    common_name="$1"
fi

if [ ! -z "$2" ]; then
    filename="$2"
fi

openssl req -subj "/commonName=*.${common_name}/" -x509 -nodes -days 9999 -newkey rsa:2048 -keyout "${cert_dir}/${filename}".key -out "${cert_dir}/${filename}".crt
