version: '3.5'

networks:
  webgateway:
    driver: bridge

# https://traefik

services:
  proxy:
    image: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
    container_name: traefik
    labels:
      - "traefik.http.routers.proxy.rule=Host(`traefik`)"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.routers.proxy.tls=true"
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert:/etc/traefik/cert
      - ./traefik.toml:/etc/traefik/traefik.toml
