version: '3.5'

networks:
  webgateway:
    driver: bridge

# https://traefik

services:
  proxy:
    image: traefik
    command: --api --docker
    container_name: traefik
    labels:
      - traefik.frontend.rule=Host:traefik
      - traefik.port=8080
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert:/etc/traefik/cert
      - ./traefik.toml:/etc/traefik/traefik.toml
