[entryPoints.web]
  address = ":80"
  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"

[entryPoints.websecure]
  address = ":443"

[api]

[providers]
    [providers.docker]
        endpoint = "unix:///var/run/docker.sock"
    [providers.file]
        filename = "/etc/traefik/dynamic.toml"

[log]
  level = "ERROR"
